version: "3.9"
services:
  db:
    image: "db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  serveur:
    image: "serveur"
    ports: 
      - "8080:8080"
    depends_on:
      - db
  client:
    image: "client"
    network_mode: host
    depends_on:
      - serveur
